// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Turnir.DAL;

#nullable disable

namespace Turnir.DAL.Migrations
{
    [DbContext(typeof(ClubContext))]
    partial class ClubContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Turnir.DAL.Model.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountDefeats")
                        .HasColumnType("int");

                    b.Property<int>("CountGames")
                        .HasColumnType("int");

                    b.Property<int>("CountGoalCo")
                        .HasColumnType("int");

                    b.Property<int>("CountGoalSC")
                        .HasColumnType("int");

                    b.Property<int>("CountWin")
                        .HasColumnType("int");

                    b.Property<string>("NameTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketsSold")
                        .HasColumnType("int");

                    b.Property<string>("TownTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Club");
                });

            modelBuilder.Entity("Turnir.DAL.Model.Players", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("GoalSkored")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Turnir.DAL.Model.Players", b =>
                {
                    b.HasOne("Turnir.DAL.Model.Club", null)
                        .WithMany("Bombardid")
                        .HasForeignKey("ClubId");
                });

            modelBuilder.Entity("Turnir.DAL.Model.Club", b =>
                {
                    b.Navigation("Bombardid");
                });
#pragma warning restore 612, 618
        }
    }
}
